# Generated by Django 2.2.4 on 2019-08-17 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholarship',
            old_name='accomodation_schol',
            new_name='accomodation_after_schol',
        ),
        migrations.RenameField(
            model_name='scholarship',
            old_name='tuition_schol',
            new_name='tuition_after_schol',
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='university',
            field=models.CharField(max_length=50),
        ),
    ]
