# Generated by Django 2.2.4 on 2019-08-17 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20190817_1343'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetail',
        ),
    ]
