# Generated by Django 2.2.4 on 2019-08-17 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_scholarship_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='timestamp',
        ),
    ]
