# Generated by Django 2.2.4 on 2019-08-17 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_remove_scholarship_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserDetail'),
        ),
    ]
